# Generated by Django 3.2.15 on 2024-04-06 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Адрес')),
                ('lat', models.FloatField(blank=True, db_index=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, db_index=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
    ]
