# Generated by Django 3.2.15 on 2024-03-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('preparing', 'Готовится'), ('delivering', 'Доставляется'), ('completed', 'Выполнен')], db_index=True, default='new', max_length=12, verbose_name='Статус'),
        ),
    ]
