# Generated by Django 3.2.15 on 2024-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20240331_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payments',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта'), ('online', 'Онлайн')], db_index=True, max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
